<?php
$a = 10;
$b = 5;
$hasilTambah = $a + $b;
$hasilKurang = $a - $b;
$hasilKali = $a * $b;
$hasilBagi = $a / $b;
$sisaBagi = $a % $b;
$pangkat = $a ** $b;
echo "Angka a: ". $a."<br>";
echo "Angka b: ". $b."<br>";
echo "Hasil $a ditambah $b adalah = $hasilTambah <br>";
echo "Hasil $a dikurang $b adalah = $hasilKurang <br>";
echo "Hasil $a dikali $b adalah = $hasilKali <br>";
echo "Hasil $a dibagi $b adalah = $hasilBagi <br>";
echo "Sisa Bagi $a dibagi $b adalah = $sisaBagi <br>";
echo "Hasil $a dipangkat $b adalah = $pangkat <br>";
echo "<br>";

$hasilSama = $a == $b;
$hasilTidakSama = $a != $b;
$hasilLebihKecil = $a < $b;
$hasilLebihBesar = $a > $b;
$hasilLebihKecilSama = $a <= $b;
$hasilLebihBesarSama = $a >= $b;
echo "Apakah $a sama dengan $b = ";
var_export($hasilSama);
echo "<br>";
echo "Apakah $a tidak sama dengan $b = ";
var_export($hasilTidakSama);
echo "<br>";
echo "Apakah $a lebih kecil dari $b = ";
var_export($hasilLebihKecil);
echo "<br>";
echo "Apakah $a lebih besar dari $b = ";
var_export($hasilLebihBesar);
echo "<br>";
echo "Apakah $a lebih kecil atau sama dengan $b = ";
var_export($hasilLebihKecilSama);
echo "<br>";
echo "Apakah $a lebih besar atau sama dengan $b = ";
var_export($hasilLebihBesarSama);
echo "<br><br>";

$hasilAnd = $a && $b;
$hasilOr = $a || $b;
$hasilNotA = !$a;
$hasilNotB = !$b;
echo "Hasil AND dari $a dan $b = ";
var_export($hasilAnd);
echo "<br>";
echo "Hasil OR dari $a dan $b = ";
var_export($hasilOr);
echo "<br>";
echo "Hasil NOT A dari $a = ";
var_export($hasilNotA);
echo "<br>";
echo "Hasil NOT B dari $b = ";
var_export($hasilNotB);
echo "<br><br>";

echo "Hasil $a += $b adalah ";
$a += $b;
echo $a."<br>";
echo "Hasil $a -= $b adalah ";
$a -= $b;
echo $a."<br>";
echo "Hasil $a *= $b adalah ";
$a *= $b;
echo $a."<br>";
echo "Hasil $a /= $b adalah ";
$a /= $b;
echo $a."<br>";
echo "Hasil $a %= $b adalah ";
$a %= $b;
echo $a."<br><br>";

$hasilIdentik = $a === $b;
echo "Apakah $a dan $b identik = ";
var_export($hasilIdentik);
echo "<br>";
$hasilTidakIdentik = $a !== $b;
echo "Apakah $a dan $b tidak identik = ";
var_export($hasilTidakIdentik);
echo "<br><br>";

echo "Ada soal cerita : Sebuah restoran memiliki 45 kursi di dalamnya.<br>.";
echo "Pada suatu malam, 28 kursi telah ditempati oleh pelanggan.<br> ";
echo "Berapa persen kursi yang masih kosong di restoran tersebut?<br>";
echo "<b>JAWABAN:</b><br>";
$totalKursi = 45;
$kursiterisi = 28;
$kursiKosong =  $totalKursi - $kursiterisi;
$persenKosong = ($kursiKosong/$totalKursi)*100;
echo "Jadi sisa kursi yang ada berjumlah $kursiKosong dengan jumlah persen yaitu ".number_format($persenKosong,2)."%";
?>